databases:
  - name: task-manager
    databaseName: task-manager
    user: mysite

services:
  - type: web
    name: mysite
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn task_manager.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: task-manager
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4