# Generated by Django 4.2.2 on 2023-06-14 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_task_author_alter_task_executor'),
        ('users', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
