# Generated by Django 4.2.2 on 2023-06-15 15:30

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tasks', '0007_alter_task_author_alter_task_executor'),
        ('users', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserTask',
        ),
        migrations.CreateModel(
            name='UserTask',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
