name: pytest-with-lint
on: push
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          pip install poetry
          make install
      - name: Create Reporter
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build
      - name: Lint
        run: |
          make lint
      - name: Add enviroment variables to .env
        run: |
          echo DATABASE_URL="sqlite:///bd.sqlite3" >> .env
          echo SECRET_KEY="some secret key 123" >> .env
      - name: Test
        run: |          
          export DJANGO_SETTINGS_MODULE=task_manager.settings
          make run_report_test
      - name: Sending Reporter
        env:
          GITHUB_TOKEN: ${{ secrets.MINILAB_ID }}
        run: |
          ./cc-test-reporter after-build -r "$GITHUB_TOKEN"